services:
  db:
    container_name: eng-db
    image: mysql:8.4.3
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 33306:3306
  adminer:
    container_name: eng-adminer
    depends_on:
      - db
    image: adminer
    ports:
      - 8088:8080
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: always
volumes:
  mysql:
